In [132]:
import os
import numpy as np
import pandas as pd
import nltk
import string
import sklearn


In [133]:
f1 = open('D:\\5th sem\\ML\\Projects\\Dataset\\SMSSpamCollection')


# Convert f1 into DataFrame

In [134]:
# Make Data Frame


#Make df for raw data
arr = np.empty((0,2)) 
for line in f1:
    l = len(line)-1
    if line[0] == 'h':
        text1 = 0
        text2 = line[4:l]
        arr = np.append(arr, np.array([[text2 , text1]]) , axis = 0)  
      
    else :
        text1 = 1
        text2 = line[5:l]
        arr = np.append(arr, np.array([[text2 , text1]]) , axis = 0)  


In [135]:
col = ["email" , "spam"]
df =  pd.DataFrame(data = arr , columns = col)


print(df)

                                                  email spam
0     Go until jurong point, crazy.. Available only ...    0
1                         Ok lar... Joking wif u oni...    0
2     Free entry in 2 a wkly comp to win FA Cup fina...    1
3     U dun say so early hor... U c already then say...    0
4     Nah I don't think he goes to usf, he lives aro...    0
...                                                 ...  ...
5569  This is the 2nd time we have tried 2 contact u...    1
5570              Will ü b going to esplanade fr home?    0
5571  Pity, * was in mood for that. So...any other s...    0
5572  The guy did some bitching but I acted like i'd...    0
5573                         Rofl. Its true to its name    0

[5574 rows x 2 columns]


In [136]:
df.shape

(5574, 2)

In [137]:
df.columns

Index(['email', 'spam'], dtype='object')

# Check Duplicates

In [138]:
df.drop_duplicates(inplace = True)

#New shape of the df
df.shape


(5171, 2)

# Check for Missing values

In [139]:
# Check for Missing data (NAN,na,NaN) for each column
df.isnull().sum()

email    0
spam     0
dtype: int64

# Tokenization

In [140]:
# download stopward package
from nltk.corpus import stopwords

In [141]:
def process_email(email):

    #1 remove punctuations
    nopunct = [char for char in email if char not in string.punctuation]
    nopunct = ''.join(nopunct)#List to string 
    
    #2 convert into lower case
    nopunct = nopunct.lower()
    
    #3 remove stopwords
    clean_words = [word for word in nopunct.split() if word not in stopwords.words('english')]
    
    return clean_words
    

In [142]:
df.reset_index(inplace = True, drop = True) 

df['email'].head().apply(process_email)

print(df)

                                                  email spam
0     Go until jurong point, crazy.. Available only ...    0
1                         Ok lar... Joking wif u oni...    0
2     Free entry in 2 a wkly comp to win FA Cup fina...    1
3     U dun say so early hor... U c already then say...    0
4     Nah I don't think he goes to usf, he lives aro...    0
...                                                 ...  ...
5166  This is the 2nd time we have tried 2 contact u...    1
5167              Will ü b going to esplanade fr home?    0
5168  Pity, * was in mood for that. So...any other s...    0
5169  The guy did some bitching but I acted like i'd...    0
5170                         Rofl. Its true to its name    0

[5171 rows x 2 columns]


## Making Vocablury of words

In [143]:
from sklearn.feature_extraction.text import CountVectorizer
vocab = CountVectorizer(analyzer=process_email).fit_transform(df['email'])
    

In [144]:
print(vocab)

  (0, 3786)	1
  (0, 4696)	1
  (0, 6445)	1
  (0, 2485)	1
  (0, 1389)	1
  (0, 1860)	1
  (0, 5686)	1
  (0, 3883)	1
  (0, 9208)	1
  (0, 4858)	1
  (0, 3016)	1
  (0, 1858)	1
  (0, 2200)	1
  (0, 3843)	1
  (0, 1156)	1
  (0, 8969)	1
  (1, 6006)	1
  (1, 4897)	1
  (1, 4664)	1
  (1, 9103)	1
  (1, 8626)	1
  (1, 6038)	1
  (2, 3571)	1
  (2, 3152)	2
  (2, 416)	1
  :	:
  (5167, 3805)	1
  (5167, 9528)	1
  (5167, 3558)	1
  (5167, 3180)	1
  (5168, 5576)	1
  (5168, 6371)	1
  (5168, 7626)	1
  (5168, 8002)	1
  (5169, 3571)	1
  (5169, 4340)	1
  (5169, 5010)	1
  (5169, 9018)	1
  (5169, 5788)	1
  (5169, 8750)	1
  (5169, 7651)	1
  (5169, 3095)	1
  (5169, 3696)	1
  (5169, 1895)	1
  (5169, 4477)	1
  (5169, 3945)	1
  (5169, 974)	1
  (5169, 1643)	1
  (5170, 5699)	1
  (5170, 8556)	1
  (5170, 7068)	1


In [145]:
vocab.shape

(5171, 9532)

In [146]:
print(vocab.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Naive Bayes Classifier

In [147]:
class NaiveBayesClassifier :
    
    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        self.X_filtered1 = self.X_train[self.y_train == 1]
        self.X_filtered0 = self.X_train[self.y_train == 0]
        self.sum_all1 = np.sum(self.X_filtered1[:,:])
        self.sum_all0 = np.sum(self.X_filtered0[:,:])
        
        
        

        
    #label => spam/ham
    def prior_prob(self, label):
        total = self.X_train.shape[0]
        label_total = np.sum(self.y_train == label)
        return label_total/total
    
    
    
    
    #Conditional probability P(Xi/label)
    def conditional_prob(self, col_name, col_value, label):
        if label == 1 :
            X_filtered = self.X_filtered1
            numerator = np.sum(X_filtered[:, col_name]) + 1
            denominator = self.sum_all1 + self.X_train.shape[1]
        else:
            X_filtered = self.X_filtered0
            numerator = np.sum(X_filtered[:, col_name]) + 1
            denominator = self.sum_all0 + self.X_train.shape[1]
        
        return float(float(numerator)/float(denominator))
    
    
    
    
    
    def predict(self, X_test):
        
        row = X_test.shape[0]
        col = X_test.shape[1]
        pp1 = self.prior_prob(1)
        pp0 = self.prior_prob(0)
        
        pred = []
        
        for i in range(row):
            s_prob =1.0
            ns_prob =1.0
            #print(i,end=" ")
            
            for j in range(col):
                if X_test[i][j] > 0:
                    s_prob = s_prob*self.conditional_prob(j , X_test[i][j],1);
                    ns_prob =ns_prob*self.conditional_prob(j , X_test[i][j],0);
                
            s_prob= s_prob*pp1
            ns_prob = ns_prob*pp0
            #print(s_prob , ns_prob)
            if s_prob>ns_prob :
                pred.append(1)
            else :
                pred.append(0)
        return pred;
    
    

In [148]:
def confusion_mat(Y_test, pred):
    #TN=0,TP=0,FN=0,FP=0
    TN = 0
    TP=0
    FN=0
    FP=0
    

    for i in range(len(Y_test)):
        
        if pred[i] == 0 and Y_test[i] == 0:
            TN=TN+1
        elif pred[i] == 1 and Y_test[i] == 1:
            TP=TP+1
        elif pred[i] == 1 and Y_test[i] == 0:
            FP=FP+1
        else:
            FN=FN+1
    
    return TN,TP,FN,FP
    
   

In [149]:
def accuracy_score(TN,TP,FN,FP):
    total = TN+TP+FN+FP
    return (TN+TP)/total


def precision_score(TN,TP,FN,FP):
    return TP/(TP+FP)


def recall_score(TN,TP,FN,FP):
    return TP/(TP+FN)


def f0pt5_score(TN,TP,FN,FP):
    p = TP/(TP+FP)
    r = TP/(TP+FN)
    return  5*p*r/(p+r)



# VALIDATION TECHNIQUES



## Train Test Split

In [150]:
# splitting in 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(vocab, df['spam'], test_size=0.20, random_state = 0)

In [151]:
X_test = X_test.toarray()
X_train = X_train.toarray()

Y_test = np.array([int(i) for i in Y_test])
Y_train = np.array([int(i) for i in Y_train])

# Y_test = Y_test.reset_index()
# Y_train = Y_train.reset_index()

In [152]:
print(type(X_test))
print(type(X_train))
print(type(Y_test))
print(type(Y_train))


print(X_test.shape)
print(Y_test.shape)
print(X_train.shape)
print(Y_train.shape)

print(X_test)
print('------------------------------------------')
print(Y_train)
print(Y_test)
# print(X_train)
#print(type(Y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(1035, 9532)
(1035,)
(4136, 9532)
(4136,)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
------------------------------------------
[1 0 0 ... 0 1 1]
[0 0 0 ... 0 0 0]


In [153]:
classifier = NaiveBayesClassifier()
classifier.fit(X_train , Y_train)

pred = classifier.predict(X_test)

print(pred)
type(pred)



[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 

list

### Performance Measures for Train Test Split 

In [154]:
#CONFUSION MATRIX

TN,TP,FN,FP = confusion_mat(Y_test,pred)

print("TN ", TN)
print("FP ", FP)
print("FN ", FN)
print("TP ", TP)


TN  872
FP  28
FN  11
TP  124


In [155]:
print("ACCURACY   : ",accuracy_score(TN,TP,FN,FP))
print("PRECISION  : ",precision_score(TN,TP,FN,FP))
print("RECALL     : ",recall_score(TN,TP,FN,FP))
print("F0.5_SCORE : ",f0pt5_score(TN,TP,FN,FP))


ACCURACY   :  0.9623188405797102
PRECISION  :  0.8157894736842105
RECALL     :  0.9185185185185185
F0.5_SCORE :  2.160278745644599


## Stratified K fold Cross Validation

In [156]:
X=vocab
Y=df['spam'].values

Y = np.array([int(i) for i in Y])

In [157]:
accuracy = []
precision = []
recall = []
f0pt5 = []

skf = StratifiedKFold(n_splits =10, random_state = None)
skf.get_n_splits(X ,Y)

for train_index, test_index in skf.split(vocab , df['spam'].values):
   # print("Train:", train_index , "Validation:", test_index)
    
    X1_train , X1_test = X[train_index], X[test_index]
    y1_train , y1_test = Y[train_index], Y[test_index]
    
 
    X1_test=X1_test.toarray()
    X1_train = X1_train.toarray()
    
    classifier.fit(X1_train,y1_train)
    prediction = classifier.predict(X1_test)
    
    TN,TP,FN,FP = confusion_mat(y1_test,prediction)
    
    print("TN ", TN , " TP " , TP , " FN " , FN , " FP ", FP)  

    accuracy.append(accuracy_score(TN,TP,FN,FP))
  
    precision.append(precision_score(TN,TP,FN,FP))

    recall.append(recall_score(TN,TP,FN,FP))

    f0pt5.append(f0pt5_score(TN,TP,FN,FP))
    

TN  443  TP  63  FN  3  FP  9
TN  440  TP  62  FN  3  FP  12
TN  444  TP  61  FN  4  FP  8
TN  446  TP  59  FN  6  FP  6
TN  443  TP  60  FN  5  FP  9
TN  445  TP  57  FN  8  FP  7
TN  440  TP  60  FN  5  FP  12
TN  443  TP  59  FN  6  FP  9
TN  435  TP  60  FN  6  FP  16
TN  444  TP  64  FN  2  FP  7


### Performance Measures of Stratified K fold validation

In [158]:
print("ACCURACIES  : ",accuracy)
print("PRECISIONS  : ",precision)
print("RECALL      : ",recall)
print("F0.5_SCORE  : ",f0pt5)

ACCURACIES  :  [0.9768339768339769, 0.9709864603481625, 0.97678916827853, 0.97678916827853, 0.9729206963249516, 0.9709864603481625, 0.9671179883945842, 0.9709864603481625, 0.9574468085106383, 0.9825918762088974]
PRECISIONS  :  [0.875, 0.8378378378378378, 0.8840579710144928, 0.9076923076923077, 0.8695652173913043, 0.890625, 0.8333333333333334, 0.8676470588235294, 0.7894736842105263, 0.9014084507042254]
RECALL      :  [0.9545454545454546, 0.9538461538461539, 0.9384615384615385, 0.9076923076923077, 0.9230769230769231, 0.8769230769230769, 0.9230769230769231, 0.9076923076923077, 0.9090909090909091, 0.9696969696969697]
F0.5_SCORE  :  [2.2826086956521743, 2.23021582733813, 2.2761194029850746, 2.269230769230769, 2.2388059701492535, 2.2093023255813953, 2.1897810218978107, 2.218045112781955, 2.1126760563380285, 2.335766423357664]


In [159]:
from statistics import mean 

print("ACCURACY    : ",mean(accuracy))
print("PRECISION   : ",mean(precision))
print("RECALL      : ",mean(recall))
print("F0.5_SCORE  : ",mean(f0pt5))

ACCURACY    :  0.9723449063874596
PRECISION   :  0.8656640861007557
RECALL      :  0.9264102564102564
F0.5_SCORE  :  2.2362551605312255
